language: python
sudo: required
dist: trusty

python:
  - 3.6

addons:
  apt:
    packages:
      - python3-pyqt5

virtualenv:
  system_site_packages: true  

install:
 - sudo apt-get update
 # Xvfb
 - sudo apt-get install -y xvfb
 # PyQt
 - sudo apt-get install -y python3-pyqt5
 # PyTest
 - pip install pytest
 - pip install pytest-qt

before_script:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sleep 3

script:
 - python3 setup.py develop
 - python3 -c "import PyQt5"
 - py.test

