sudo: false
language: python

python:
  - 2.7

addons:
  apt:
    packages:
      - python-pyside

virtualenv:
  system_site_packages: true  

install:
 # PyTest
 - pip install pytest
 - pip install pytest-qt

before_script:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sleep 3

script:
 - python setup.py develop
 - py.test

