language: python
sudo: required
dist: trusty

python:
  - 3.4

addons:
  apt:
    packages:
      - python-pyqt4

virtualenv:
  system_site_packages: true  

install:
 - sudo apt-get update
 # Xvfb
 - sudo apt-get install -y xvfb
 # PyQt
 - sudo apt-get install -y python-pyqt4
 # PyTest
 - pip install pytest
 - pip install pytest-qt

before_script:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sleep 3

script:
 - python setup.py develop
 - python -c "import PyQt4"
 - py.test

